-- Seed data for menu_items table
-- Best Seller
INSERT INTO menu_items (name, description, price, category) VALUES
('Caramel Macchiato', 'Sweet caramel with smooth espresso and steamed milk', 'Rp 42.000', 'bestseller'),
('Matcha Latte', 'Premium matcha with creamy oat milk', 'Rp 38.000', 'bestseller'),
('Chocolate Cake', 'Decadent chocolate cake with ganache frosting', 'Rp 55.000', 'bestseller'),
('Croissant', 'Buttery, flaky French croissant', 'Rp 28.000', 'bestseller'),
('Vanilla Latte', 'Smooth espresso with vanilla and steamed milk', 'Rp 36.000', 'bestseller'),
('Red Velvet Cake', 'Classic red velvet with cream cheese frosting', 'Rp 58.000', 'bestseller'),
('Iced Caramel Latte', 'Cold caramel latte with ice and whipped cream', 'Rp 40.000', 'bestseller'),
('Chocolate Chip Muffin', 'Fresh baked muffin with chocolate chips', 'Rp 30.000', 'bestseller'),
('Cappuccino', 'Espresso with steamed milk and foam', 'Rp 35.000', 'bestseller'),
('Strawberry Cheesecake', 'Creamy cheesecake with fresh strawberries', 'Rp 56.000', 'bestseller'),
('Hazelnut Latte', 'Rich hazelnut flavor with espresso and milk', 'Rp 39.000', 'bestseller'),
('Almond Croissant', 'Buttery croissant filled with almond cream', 'Rp 32.000', 'bestseller'),
('Iced Matcha', 'Refreshing cold matcha with ice', 'Rp 37.000', 'bestseller'),
('New York Cheesecake', 'Classic creamy New York style cheesecake', 'Rp 52.000', 'bestseller'),
('Mocha Frappe', 'Blended mocha with ice and whipped cream', 'Rp 43.000', 'bestseller'),
('Blueberry Scone', 'Buttery scone with fresh blueberries', 'Rp 29.000', 'bestseller'),
('White Chocolate Mocha', 'Espresso with white chocolate and milk', 'Rp 41.000', 'bestseller'),
('Lemon Tart', 'Tangy lemon curd in buttery pastry shell', 'Rp 45.000', 'bestseller'),
('Cold Brew', 'Smooth cold-brewed coffee, served over ice', 'Rp 32.000', 'bestseller'),
('Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 'Rp 48.000', 'bestseller');

-- Coffee
INSERT INTO menu_items (name, description, price, category) VALUES
('Espresso', 'Rich and bold espresso with a perfect crema', 'Rp 25.000', 'coffee'),
('Americano', 'Espresso with hot water, bold and smooth', 'Rp 28.000', 'coffee'),
('Cappuccino', 'Espresso with steamed milk and foam', 'Rp 35.000', 'coffee'),
('Latte', 'Espresso with steamed milk, smooth and creamy', 'Rp 35.000', 'coffee'),
('Caramel Macchiato', 'Sweet caramel with smooth espresso and steamed milk', 'Rp 42.000', 'coffee'),
('Mocha', 'Espresso with chocolate and steamed milk', 'Rp 40.000', 'coffee'),
('Flat White', 'Double espresso with microfoam milk', 'Rp 38.000', 'coffee'),
('Cold Brew', 'Smooth cold-brewed coffee, served over ice', 'Rp 32.000', 'coffee'),
('Vanilla Latte', 'Smooth espresso with vanilla and steamed milk', 'Rp 36.000', 'coffee'),
('Hazelnut Latte', 'Rich hazelnut flavor with espresso and milk', 'Rp 39.000', 'coffee'),
('White Chocolate Mocha', 'Espresso with white chocolate and milk', 'Rp 41.000', 'coffee'),
('Cortado', 'Equal parts espresso and steamed milk', 'Rp 33.000', 'coffee'),
('Affogato', 'Espresso poured over vanilla ice cream', 'Rp 38.000', 'coffee'),
('Long Black', 'Double espresso with hot water', 'Rp 30.000', 'coffee'),
('Piccolo Latte', 'Small latte with ristretto shot', 'Rp 32.000', 'coffee'),
('Caffe Breve', 'Espresso with half-and-half instead of milk', 'Rp 37.000', 'coffee'),
('Red Eye', 'Drip coffee with a shot of espresso', 'Rp 34.000', 'coffee'),
('Irish Coffee', 'Coffee with Irish whiskey and cream', 'Rp 45.000', 'coffee'),
('Vietnamese Coffee', 'Strong coffee with condensed milk', 'Rp 36.000', 'coffee'),
('Turkish Coffee', 'Traditional finely ground coffee, unfiltered', 'Rp 35.000', 'coffee');

-- Non Coffee
INSERT INTO menu_items (name, description, price, category) VALUES
('Matcha Latte', 'Premium matcha with creamy oat milk', 'Rp 38.000', 'noncoffee'),
('Chocolate Latte', 'Rich chocolate with steamed milk', 'Rp 36.000', 'noncoffee'),
('Green Tea', 'Premium Japanese green tea', 'Rp 22.000', 'noncoffee'),
('Earl Grey Tea', 'Classic bergamot-scented black tea', 'Rp 22.000', 'noncoffee'),
('Fresh Orange Juice', 'Freshly squeezed orange juice', 'Rp 28.000', 'noncoffee'),
('Lemonade', 'Fresh lemonade with a hint of mint', 'Rp 26.000', 'noncoffee'),
('Smoothie Berry', 'Mixed berries with yogurt and honey', 'Rp 38.000', 'noncoffee'),
('Hot Chocolate', 'Rich and creamy hot chocolate', 'Rp 32.000', 'noncoffee'),
('Iced Matcha', 'Refreshing cold matcha with ice', 'Rp 37.000', 'noncoffee'),
('Chai Latte', 'Spiced tea with steamed milk', 'Rp 35.000', 'noncoffee'),
('Jasmine Tea', 'Fragrant jasmine green tea', 'Rp 24.000', 'noncoffee'),
('Peach Iced Tea', 'Refreshing peach flavored iced tea', 'Rp 27.000', 'noncoffee'),
('Mango Smoothie', 'Fresh mango blended with yogurt', 'Rp 39.000', 'noncoffee'),
('Strawberry Smoothie', 'Fresh strawberries with banana and yogurt', 'Rp 37.000', 'noncoffee'),
('Avocado Smoothie', 'Creamy avocado with condensed milk', 'Rp 35.000', 'noncoffee'),
('Watermelon Juice', 'Fresh watermelon juice, chilled', 'Rp 25.000', 'noncoffee'),
('Ginger Tea', 'Warming ginger tea with honey', 'Rp 23.000', 'noncoffee'),
('Chamomile Tea', 'Calming herbal chamomile tea', 'Rp 24.000', 'noncoffee'),
('Coconut Water', 'Fresh young coconut water', 'Rp 30.000', 'noncoffee'),
('Mint Lemonade', 'Refreshing mint and lemon blend', 'Rp 28.000', 'noncoffee');

-- Snack
INSERT INTO menu_items (name, description, price, category) VALUES
('Croissant', 'Buttery, flaky French croissant', 'Rp 28.000', 'snack'),
('Chocolate Cake', 'Decadent chocolate cake with ganache frosting', 'Rp 55.000', 'snack'),
('Tiramisu', 'Classic Italian dessert with coffee and mascarpone', 'Rp 48.000', 'snack'),
('Cheesecake', 'Creamy New York style cheesecake', 'Rp 52.000', 'snack'),
('Blueberry Muffin', 'Fresh baked muffin with blueberries', 'Rp 32.000', 'snack'),
('Chocolate Chip Cookie', 'Warm, gooey chocolate chip cookies', 'Rp 25.000', 'snack'),
('Banana Bread', 'Moist banana bread with walnuts', 'Rp 35.000', 'snack'),
('Cinnamon Roll', 'Sweet cinnamon roll with cream cheese frosting', 'Rp 38.000', 'snack'),
('Almond Croissant', 'Buttery croissant filled with almond cream', 'Rp 32.000', 'snack'),
('Red Velvet Cake', 'Classic red velvet with cream cheese frosting', 'Rp 58.000', 'snack'),
('Strawberry Cheesecake', 'Creamy cheesecake with fresh strawberries', 'Rp 56.000', 'snack'),
('Blueberry Scone', 'Buttery scone with fresh blueberries', 'Rp 29.000', 'snack'),
('Lemon Tart', 'Tangy lemon curd in buttery pastry shell', 'Rp 45.000', 'snack'),
('Chocolate Brownie', 'Rich fudgy chocolate brownie', 'Rp 33.000', 'snack'),
('Apple Pie', 'Classic apple pie with cinnamon', 'Rp 42.000', 'snack'),
('Carrot Cake', 'Moist carrot cake with cream cheese frosting', 'Rp 48.000', 'snack'),
('Pecan Pie', 'Sweet pecan pie with caramel', 'Rp 46.000', 'snack'),
('Chocolate Eclair', 'Cream-filled pastry with chocolate glaze', 'Rp 38.000', 'snack'),
('Raspberry Danish', 'Flaky pastry with raspberry filling', 'Rp 36.000', 'snack'),
('Pistachio Macaron', 'Delicate French macaron with pistachio', 'Rp 28.000', 'snack');

-- Merchandise
INSERT INTO menu_items (name, description, price, category) VALUES
('Luxe Cafe T-Shirt', 'Premium cotton t-shirt with logo', 'Rp 150.000', 'merchandise'),
('Luxe Cafe Tumbler', 'Insulated stainless steel tumbler 500ml', 'Rp 180.000', 'merchandise'),
('Luxe Cafe Mug', 'Ceramic mug with logo design', 'Rp 95.000', 'merchandise'),
('Luxe Cafe Tote Bag', 'Canvas tote bag with logo', 'Rp 120.000', 'merchandise'),
('Coffee Beans Pack', 'Premium coffee beans 250gr', 'Rp 125.000', 'merchandise'),
('Luxe Cafe Hoodie', 'Comfortable hoodie with logo', 'Rp 280.000', 'merchandise'),
('Luxe Cafe Cap', 'Adjustable cap with embroidered logo', 'Rp 110.000', 'merchandise'),
('Coffee Grinder', 'Manual coffee grinder for home use', 'Rp 350.000', 'merchandise'),
('French Press', 'Glass French press 500ml', 'Rp 220.000', 'merchandise'),
('Pour Over Set', 'Complete pour over coffee brewing set', 'Rp 195.000', 'merchandise'),
('Coffee Scale', 'Digital coffee scale with timer', 'Rp 275.000', 'merchandise'),
('Luxe Cafe Apron', 'Professional barista apron with logo', 'Rp 165.000', 'merchandise'),
('Coffee Syrup Set', 'Set of 3 flavored coffee syrups', 'Rp 140.000', 'merchandise'),
('Luxe Cafe Notebook', 'Premium notebook with cafe logo', 'Rp 85.000', 'merchandise'),
('Coffee Gift Set', 'Gift set with beans, mug, and syrup', 'Rp 320.000', 'merchandise'),
('Luxe Cafe Stickers', 'Set of 10 premium vinyl stickers', 'Rp 45.000', 'merchandise'),
('Coffee Thermometer', 'Digital coffee temperature gauge', 'Rp 155.000', 'merchandise'),
('Luxe Cafe Keychain', 'Metal keychain with logo design', 'Rp 65.000', 'merchandise'),
('Coffee Filters Pack', 'Premium paper filters 100pcs', 'Rp 75.000', 'merchandise'),
('Luxe Cafe Gift Card', 'Gift card with custom design', 'Rp 100.000', 'merchandise');

